### ISSUE TITLE
Error on ng build

### ISSUE THREAD

**Issue by X-Anonymous-Y** [VahidN/angular-template-driven-forms-lab#1]
windows 10 pro - 64 bit
git v.2.16.2 64 bit
node v.9.9.0 - 64 bit
visual studio code v.1.21.1 - 64 bit
xampp v.7.2.3-0 - 32 bit

ng build --watch

$ ng build --watch
Your global Angular CLI version (1.7.3) is greater than your local
version (1.7.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Date: 2018-04-09T19:25:59.464Z
Hash: d8acb5c56782260d7ddb
Time: 3637ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 277 bytes [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 297 bytes [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 12.9 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 193 kB [initial] [rendered]

ERROR in src/app/shared/confirm-modal/confirm-modal.component.ts(15,8): error TS1005: '=' expected.
src/app/shared/confirm-modal/confirm-modal.component.ts(15,9): error TS1109: Expression expected.
src/app/shared/confirm-modal/confirm-modal.component.ts(15,11): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
src/app/shared/confirm-modal/confirm-modal.component.ts(15,30): error TS1109: Expression expected.
src/app/shared/confirm-modal/confirm-modal.component.ts(17,1): error TS1128: Declaration or statement expected.

**Comment by VahidN** [comment]
- I updated the package.json file.
- I think you are using an outdated typescript compiler. try running the following commands first
```
npm install -g typescript
npm update -g
```
